### ISSUE TITLE
Provenance out of date

### ISSUE THREAD

**Issue by JoeMatt** [Randomblock1/randomsource#1]
Provenance is on 2.0.4 now.
https://provenance-emu.com

We also have our own altstore source.

FYI, you can use the altstore URI to auto-add sources to altstore beta.
eg; altstore://source?url=https://provenance-emu.com/apps.json

**Comment by Randomblock1** [comment]
OK, removed it. The goal is to provide tweaked apps without official support, so I'll add a message telling them what to do. (I'm not even sure if anyone uses this still, to be honest).
